apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: todobackend
  name: todobackend
spec:
  ports:
  - name: 8080-3001
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: todobackend
status:
  loadBalancer: {}
