apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: todobackend
  name: todobackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todobackend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todobackend
    spec:
      containers:
      - image: burakgundogdu/todo-backend:v1
        name: todo-app
        ports:
        - containerPort: 3001
        env:
         - name: MONGO_HOST
           value : "todomongo"
        resources: {}
status: {}
